title: Custom By Design
email: jwoytas@custombydesign.ca
description: >- # this means to ignore newlines until "baseurl:"
  All the best designs are Custom By Design
baseurl: "" 
url: "" 
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
